### ISSUE TITLE
Using native libraries on applets causes applet to fail after multiple tries

### ISSUE THREAD

**Issue by Vulpovile** [andreja6/Internet-Adventure#2]
Exception in thread "Thread-38" java.lang.UnsatisfiedLinkError: Native LibraryTemp\lwjglcache\localhost\appletloadertest\natives\lwjgl.dll already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:132)
	at com.mojang.minecraft.Minecraft.init(Minecraft.java:96)
	at com.mojang.minecraft.Minecraft.run(Minecraft.java:210)
	at java.lang.Thread.run(Unknown Source)

Happens only when multiple applets use the same library, and if you reload the same applet. May take a few refreshes to reproduce.

**Comment by Vulpovile** [comment]
Will be solved when seperate_jvm is implemented

**Comment by Vulpovile** [comment]
Implemented seperate_jvm which addressed this
